website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import login_required, current_user
from .models import Players, League, GameDay, LeagueClassification, Game, GameDayClassification, GameDayPlayer, ELOranking, ELOrankingHist
from . import db
import json, os, threading
from datetime import datetime, date, timedelta
from sqlalchemy import and_, func, cast, String, text, desc, case, literal_column


views =  Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
    try:
        leagues_data = League.query.order_by(League.lg_status, League.lg_endDate.desc()).all()
    except Exception as e:
        print(f"Error: {e}")
    return render_template("index.html", user=current_user, result=leagues_data)

@views.route('/testIndex', methods=['GET', 'POST'])
def testIndex():
    leagues_data = League.query.order_by(League.lg_status, League.lg_endDate.desc()).all()
    return render_template("testIndex.html", user=current_user, result=leagues_data)


@views.route('/players', methods=['GET', 'POST'])
def players():
    players_data = Players.query.order_by(Players.pl_name).all()
    return render_template('players.html', user=current_user, players=players_data)

@views.route('/league/<leagueID>')
def league_detail(leagueID):
    league_data = League.query.filter_by(lg_id=leagueID).first()
    if league_data.lg_id_tp != 6:
        result = GameDay.query.filter_by(gd_idLeague=leagueID).all()
    else:
        result = GameDay.query.filter_by(gd_idLeague=leagueID).order_by(desc(GameDay.gd_date)).all()

    classification = LeagueClassification.query.filter_by(lc_idLeague=leagueID).order_by(desc(LeagueClassification.lc_ranking)).all()
    return render_template("league_detail.html", user=current_user, league=league_data, result=result, classification=classification) 

@views.route('/gameDay/<gameDayID>')
def gameDay_detail(gameDayID):
    gameDay_data = GameDay.query.filter_by(gd_id=gameDayID).first()
    results = Game.query.filter_by(gm_idGameDay=gameDayID).order_by(Game.gm_timeStart).all()
    classifications = GameDayClassification.query.filter_by(gc_idGameDay=gameDayID).order_by(desc(GameDayClassification.gc_ranking)).all()
    return render_template("gameDay_detail.html", user=current_user, gameDay=gameDay_data, result=results, classification=classifications) 

# management
@views.route('/managementLeague', methods=['GET', 'POST'])
@login_required
def managementLeague():
    # updates avulso
    # updates_avulso()

    leagues_data = League.query.order_by(League.lg_status, League.lg_endDate.desc()).all()
    return render_template("managementLeague.html", user=current_user, result=leagues_data)

@views.route('/managementLeague_detail/<leagueID>', methods=['GET', 'POST'])
@login_required
def managementLeague_detail(leagueID):
    league_data = League.query.filter_by(lg_id=leagueID).first()
    result = GameDay.query.filter_by(gd_idLeague=leagueID).order_by(desc(GameDay.gd_date)).all()
    classification = LeagueClassification.query.filter_by(lc_idLeague=leagueID).order_by(desc(LeagueClassification.lc_ranking)).all()
    return render_template("managementLeague_detail.html", user=current_user, league=league_data, result=result, classification=classification)

@views.route('/managementPlayers', methods=['GET', 'POST'])
@login_required
def managementPlayers():
    players_data = Players.query.order_by(Players.pl_name).all()
    return render_template("managementPlayers.html", user=current_user, players=players_data)

@views.route('/rankingELO')
def rankingELO():
    results = db.session.execute(
        text(f"SELECT pl_id, pl_name, ROUND(pl_rankingNow, 2) as pl_rankingNow, ROUND(pl_totalRankingOpo, 2) as pl_totalRankingOpo, pl_wins, pl_losses, pl_totalGames, CASE WHEN instr(pl_name, '\"') > 0 AND instr(substr(pl_name, instr(pl_name, '\"') + 1), '\"') > 0 THEN substr(pl_name, instr(pl_name, '\"') + 1, instr(substr(pl_name, instr(pl_name, '\"') + 1), '\"') - 1) ELSE pl_name END AS pl_name_short FROM tb_ELO_ranking WHERE pl_id in (SELECT pl_id from tb_players where pl_ranking_stat='Y') order by pl_rankingNow desc"),
    ).fetchall()   
    
    return render_template("rankingELO.html", user=current_user, result=results)

@views.route('/create_league', methods=['GET', 'POST'])
@login_required
def create_league():
    # leagues_data = League.query.order_by(League.lg_status).all()
    return render_template("create_league.html", user=current_user)

@views.route('/recalculate_ELO_full')
def recalculate_ELO_full():
    calculate_ELO_full()
    # print("recalculate finished")
    results = db.session.execute(
        text(f"SELECT pl_id, pl_name, ROUND(pl_rankingNow, 2) as pl_rankingNow, ROUND(pl_totalRankingOpo, 2) as pl_totalRankingOpo, pl_wins, pl_losses, pl_totalGames FROM tb_ELO_ranking  order by pl_rankingNow desc"),
    ).fetchall()   
    # print("results loaded")
    # if results:
    #     print("there are results")
    # if current_user:
    #     print("there is user")
    return render_template("rankingELO.html", user=current_user, result=results)

@views.route('/create_game_day/<leagueID>', methods=['GET', 'POST'])
@login_required
def create_game_day(leagueID):
    league_data = League.query.filter_by(lg_id=leagueID).first()
    # leagues_data = League.query.order_by(League.lg_status).all()
    return render_template("create_game_day.html", user=current_user, league=league_data)

@views.route('/create_player', methods=['GET', 'POST'])
@login_required
def create_player():
    return render_template("create_player.html", user=current_user)

@views.route('/delete_player/<playerID>')
@login_required
def delete_player(playerID):
    try:
        # Delete Player
        Players.query.filter_by(pl_id=playerID).delete()

        # Commit the changes to the database
        db.session.commit()

    except Exception as e:
        print(f"Error: {e}")
        # Handle the error, maybe log it or display a message to the user
    
    players_data = Players.query.order_by(Players.pl_name).all()
    return render_template('players.html', user=current_user, players=players_data)

@views.route('/deleteLeague/<leagueID>')
@login_required
def deleteLeague(leagueID):
    try:
        # Delete League
        League.query.filter_by(lg_id=leagueID).delete()

        # Commit the changes to the database
        db.session.commit()

        #Delete Gamedays
        GameDay.query.filter(gd_idLeague=leagueID).delete()
        # Commit the changes to the database
        db.session.commit()

    except Exception as e:
        print(f"Error: {e}")
        # Handle the error, maybe log it or display a message to the user
    
    leagues_data = League.query.order_by(League.lg_status, League.lg_endDate.desc()).all()
    return render_template("managementLeague.html", user=current_user, result=leagues_data)

@views.route('/managementGameDay_detail/<gameDayID>')
@login_required
def managementGameDay_detail(gameDayID):
    gameDay_data = GameDay.query.filter_by(gd_id=gameDayID).first()
    results = Game.query.filter_by(gm_idGameDay=gameDayID).order_by(Game.gm_timeStart).all()
    classifications = GameDayClassification.query.filter_by(gc_idGameDay=gameDayID).order_by(desc(GameDayClassification.gc_ranking)).all()
    gameDayPlayers = GameDayPlayer.query.filter_by(gp_idGameDay=gameDayID).all()
    number_of_teamsGD = len(gameDayPlayers)
    league = League.query.filter_by(lg_id=gameDay_data.gd_idLeague).first()
    if league.lg_id_tp != 6:
        number_of_teams_league = league.lg_nbrTeams
    else:
        number_of_teams_league = gameDay_data.gd_teamNum
    players_data = Players.query.order_by(Players.pl_name).all()
    league_id = league.lg_id
    type_gameday = league.lg_id_tp
    gameDay_id = gameDayID
    playersGameDay = GameDayPlayer.query.filter_by(gp_idGameDay=gameDayID).order_by(GameDayPlayer.gp_team.asc(), GameDayPlayer.gp_id.asc()).all()
    # Organize players by team
    teams = {}
    for player in playersGameDay:
        if player.gp_team not in teams:
            teams[player.gp_team] = []
        teams[player.gp_team].append(player)
    return render_template("managementGameDay_detail.html", user=current_user, gameDay=gameDay_data, result=results, classification=classifications, number_of_teamsGD=number_of_teamsGD, number_of_teams_league=number_of_teams_league, players_data=players_data, gameDayPlayers=gameDayPlayers, league_id=league_id, gameDay_id=gameDay_id, teams=teams, type_gameday=type_gameday) 

@views.route('/print_page/<gameDayID>')
@login_required
def print_page(gameDayID):
    gameDay_data = GameDay.query.filter_by(gd_id=gameDayID).first()
    league_id = gameDay_data.gd_idLeague
    # Get Title League
    try:
        league_detail = db.session.execute(
            text(f"SELECT lg_name FROM tb_league WHERE lg_id=:lg_id"),
            {"lg_id": league_id}
        ).fetchone()
        leagueName = league_detail[0]
    except Exception as e:
        print("Error1:", e)

    # Get Title GameDay
    try:
        results0 = db.session.execute(
            text(f"SELECT gd_id FROM tb_gameday WHERE gd_idLeague=:lg_id ORDER BY gd_date ASC"),
            {"lg_id": league_id},
        ).fetchall()
        num_jornada = 0
        gameDayName = ""
        for data0 in results0:
            num_jornada += 1
            if str(data0[0]) == gameDayID:
                gameDayName = f"{num_jornada}ª Jornada"
    except Exception as e:
        print("Error2:", e)

    # Get Teams
    try:
        teams = db.session.execute(
            text(f"SELECT gp_namePlayer FROM tb_gameDayPlayer WHERE gp_idLeague=:lg_id AND gp_idGameDay=:gd_id ORDER BY gp_team ASC"),
            {"lg_id": league_id, "gd_id": gameDayID},
        ).fetchall()
        teamA = teams[0][0] + " / " + teams[1][0]
        teamB = teams[2][0] + " / " + teams[3][0]
        teamC = teams[4][0] + " / " + teams[5][0]

website/templates/create_league.html
{% extends "base.html" %} {% block title %}Rio Padel League{% endblock %} {% block content %}
<div class="clearfix"></div>
	
<div class="container-fluid">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">Criar Nova Liga</div>
                <hr>
                    <form action="{{ url_for('views.insertLeague') }}" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="input-6">Nome</label>
                        <input type="text" class="form-control form-control-rounded" id="input-6" placeholder="Nome da Liga" name="league_name">
                    </div>
                    <div class="form-group">
                        <label for="input-7">Nivel</label>
                        <select  class="form-control form-control-rounded" id="input-7" name="league_level">
                            <option class="form-control" value="M4M5" name="league_level" selected >M4M5</option>
                            <option class="form-control" value="M3M4" name="league_level">M3M4</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="input-8">Estado</label>
                        <select  class="form-control form-control-rounded" id="input-8" name="league_status">
                            <option class="form-control" value="1 - Ativo" name="league_status" selected>Ativo</option>
                            <option class="form-control" value="0 - Inativo" name="league_status">Inativo</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="input-9">Número Jornadas</label>
                        <input type="number" class="form-control form-control-rounded" id="input-9" placeholder="Jornadas Liga" name="league_numGameDays">
                    </div>
                    <div class="form-group">
                        <label for="input-10">Número equipas</label>
                        <input type="number" class="form-control form-control-rounded" id="input-10" placeholder="Número equipas por jornada" name="league_teams">
                    </div>
                    <div class="form-group">
                        <label for="input-11">Data Inicio Liga</label>
                        <input type="date" class="form-control form-control-rounded" id="input-11" placeholder="Calendario escolher data inicio" name="league_dateStart">
                    </div>
                    <div class="form-group">
                        <label for="input-12">Data Fim Liga</label>
                        <input type="date" class="form-control form-control-rounded" id="input-12" placeholder="Calendario escolher data fim" name="league_dateEnd">
                    </div>
                    <div class="form-group">
                        <label for="timeStart">Hora Inicio</label>
                        <input type="time" class="form-control form-control-rounded" id="timeStart" placeholder="Hora Inicio" name="timeStart">
                    </div>
                    <div class="form-group">
                        <label for="league_billboard">Cartaz Grande</label>
                        <input type="file" class="form-control form-control-rounded" id="league_billboard" placeholder="Cartaz da liga" name="league_billboard">
                    </div>
                    <div class="form-group">
                        <label for="league_billboard_S">Cartaz Pequeno</label>
                        <input type="file" class="form-control form-control-rounded" id="league_billboard_S" placeholder="Cartaz da liga pequeno" name="league_billboard_S">
                    </div>
                    <div class="form-group">
                        <label for="input-14">Tipo de Liga</label>
                        <select class="form-control form-control-rounded" id="league_type" name="league_type">
                            <option value="Liga">Liga</option>
                            <option value="Avulso">NonStop sem Liga</option>
                            <option value="Outro">Outro</option>
                            <option value="Mexicano">Mexicano</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-light btn-round px-5"><i class="icon-save"></i> Criar Liga</button>
                    </div>
                    </form>
            </div>
        </div>
    </div>
    <!--start overlay-->
    <div class="overlay toggle-menu"></div>
    <!--end overlay-->

</div>
<!-- End container-fluid-->
    

{% endblock %}

website/templates/indexOld.html
{% extends "base.html" %} {% block title %}XT Padel League{% endblock %} 
{% block content %}
<!-- WPT -->
<link href="../static/css/app-min.css" rel="stylesheet"/>

<!-- Tabela das ligas -->
<div class="row">
  <div class="col-lg-12">
      <div class="card">
          <div class="card-body">
              <h5 class="card-title">Ligas</h5>
              <div class="table-responsive">
                  <table class="table table-hover">
                      <thead>
                          <tr>
                          </tr>
                      </thead>
                      <tbody>
                          {% for data in result %}
                              <div class="l-grid l-grid--flex l-grid--flex-centered">
                                  <div class="c-tournaments c-tournaments--new c-tournaments--fixed">
                                      <div class="c-tournaments__top-block">
                                          <div class="c-tournaments__top-block__title">
                                              <span class="c-tournaments__line"></span>
                                              <h5>{{ data['lg_status'][4:] }}</h5>
                                          </div>
                                      </div>
                                      <div class="c-tournaments__container">
                                          <div class="c-tournaments__poster">
                                              {% set bigPhoto = "static/photos/leagues/" + data['lg_id']|string + ".jpg"  %}

                                              {% set smallPhoto = "static/photos/leagues/" + data['lg_id']|string + "s.jpg"  %}

                                              <a target="_blank" href="{{ bigPhoto }}" class="c-trigger">
                                                  <img src="{{ bigPhoto }}">
                                              </a>
                                              <div class="c-tournaments__img c-tournaments__img--bg" style="background-image: url({{ bigPhoto }});"></div>
                                          </div>
                                          <div class="c-tournaments__content">
                                              <header class="c-tournaments__top-card">
                                                  <div class="c-tournaments__header" style="background:url('{{ smallPhoto }}');"></div>
                                                  <p class="c-tournaments__date">De {{ data['lg_startDate'] }} a {{ data['lg_endDate'] }}</p>
                                              </header>
                                              <footer class="c-tournaments__bottom-card">
                                                  <div class="c-tournaments__header">
                                                      <h3 class="c-tournaments__title">{{ data['lg_name'] }}</h3>
                                                      <p class="c-tournaments__cat">Categoria: {{ data['lg_level'] }}</p>
                                                  </div>
                                              </footer>
                                              <div class="c-tournaments__triggers">
                                                  <a class="c-btn c-btn--secondary" href="{{ url_for('views.league_detail', leagueID=data['lg_id']) }}">+ DETALHE</a>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>

                          {% endfor %}
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
  </div>
</div><!-- End Row -->



{% endblock %}

website/templates/managementLeague.html
{% extends "base.html" %} {% block title %}XT Padel League{% endblock %} 
{% block content %}
<!-- WPT -->
<link href="../static/css/app-min.css" rel="stylesheet"/>

<!-- button to create new league -->
<div class="container">
    <div class="row">
        <div class="col-md-12 text-right">
            <a href="{{ url_for('views.create_league') }}" class="btn btn-light btn-round px-5"><i class="icon-plus"></i> Criar Liga</a>
        </div>
    </div>
</div>
<br>

<!-- Table of Leagues -->
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Ligas</h5>
                <div class="row">
                    {% for data in result %}
                    <div class="col-lg-4">
                        <div class="slides__item">
                            {% set bigPhoto = "static/photos/leagues/" + data['lg_id']|string + ".jpg"  %}
                            {% set smallPhoto = "static/photos/leagues/" + data['lg_id']|string + "s.jpg"  %}
                            <article id="card-da7c7d20-43b3-11e8-8674-52540049669c" class="card"><a
                                    href="{{ url_for('views.managementLeague_detail', leagueID=data['lg_id']) }}"
                                    class="card__header-link">
                                    <header class="card__header"
                                        style="background-image: url({{ smallPhoto }});">
                                        <!-- <h1>{{ data['lg_name'] }}</h1> -->
                                    </header>
                                </a>
                                <div class="card__body">
                                    <div class="card__address">
                                        <i class="zmdi zmdi-accounts"></i>
                                        <div class="card__address__street">{{ data['lg_name'] }}</div>
                                    </div>
                                    <div class="card__address">
                                        <i class="zmdi zmdi-calendar"></i>
                                        <div class="card__address__street">De {{ data['lg_startDate'] }} a {{ data['lg_endDate'] }}</div>
                                    </div>
                                    <div class="card__address">
                                        {% if data['lg_status'][4:]=="Ativo" %}
                                            <i class="zmdi zmdi-play-circle-outline"></i>
                                        {% else %}
                                            <i class="zmdi zmdi-stop"></i>
                                        {% endif %}
                                        <div class="card__address__street">{{ data['lg_status'][4:] }}</div>
                                    </div>
                                    <a role="button" class="button button--regular"
                                        href="{{ url_for('views.managementLeague_detail', leagueID=data['lg_id']) }}"
                                        tabindex="0">
                                        <div>DETALHE</div>
                                    </a>
                                </div>
                            </article>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div><!-- End Row -->

{% endblock %}

website/templates/managementLeague_detail.html
{% extends "base.html" %} {% block title %}XT Padel League{% endblock %} 
{% block content %}
<!-- Show front page of league -->

<!-- button to create new gameday -->
<!-- Criar novas jornadas só em ligas do tipo 6, ligas avulso -->
{% if league.lg_id_tp == 6 %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-right">
            <a href="{{ url_for('views.create_game_day', leagueID=league.lg_id) }}" class="btn btn-light btn-round px-5"><i class="icon-plus"></i> Criar Jornada</a>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-12 text-right">
            <a href="{{ url_for('views.deleteLeague', leagueID=league.lg_id) }}" class="btn btn-danger btn-round px-5"><i class="icon-minus"></i> Apagar Liga</a>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-right">
            <a href="{{ url_for('views.deleteLeague', leagueID=league.lg_id) }}" class="btn btn-danger btn-round px-5"><i class="icon-minus"></i> Apagar Liga</a>
        </div>
    </div>
</div>
{% endif %}

<!-- Table of gamedays -->
<div class="row">
    {% for data in result %}
    <div class="col-lg-3">
        <a href="{{ url_for('views.managementGameDay_detail', gameDayID=data['gd_id']) }}">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{{ league.lg_name }}</h5>
                </div>
                <div class="card-body">
                    <br>Data : {{ data['gd_date'] }}</br>
                    <br>Estado : {{ data['gd_status'] }}</br>
                    {% if data['gd_status'] == 'Terminado' %}
                        <br>Vencedores: {{ display_short_name(data['gd_nameWinner1']) }} / {{ display_short_name(data['gd_nameWinner2']) }}</br>
                    {% else %}
                        <br>Vencedores: </br>
                    {% endif %}
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div><!-- End Row -->

{% if league.lg_typeOfLeague != 'Avulso' %}
<!-- Table of classification -->
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Classificação Geral</h5>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <!-- <th scope="col">#</th> -->
                                <th class="" scope="col">Nome</th>
                                <th class="" scope="col">Pts</th>
                                <th class="d-none d-md-table-cell" scope="col">PG</th>
                                <th class="d-none d-md-table-cell" scope="col">PP</th>
                                <th class="d-none d-xl-table-cell" scope="col">JG</th>
                                <th class="d-none d-xl-table-cell" scope="col">JP</th>
                                <th class="d-none d-xl-table-cell" scope="col">JD</th>
                                <th class="d-none d-xl-table-cell" scope="col">Ranking</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for data in classification %}
                            <tr data-href="{{ url_for('views.player_detail', playerID=data['lc_idPlayer']) }}">
                                <!-- <th scope="row">{{ data['lc_idPlayer'] }}</th> -->
                                <td class=""  onclick="window.location.href='{{ url_for('views.player_detail', playerID=data['lc_idPlayer']) }}';">
                                    <img src="{{ url_for('views.display_user_image', userID=data['lc_idPlayer'] ) }}" alt="{{ data['lc_namePlayer'] }}" class="rounded-circle" width="40">
                                    {{ display_short_name(data['lc_namePlayer']) }}
                                </td>
                                <td class="" onclick="window.location.href='{{ url_for('views.player_detail', playerID=data['lc_idPlayer']) }}';">{{ data['lc_points'] }}</td>
                                <td class="d-none d-md-table-cell" onclick="window.location.href='{{ url_for('views.player_detail', playerID=data['lc_idPlayer']) }}';">{{ data['lc_wins'] }}</td>
                                <td class="d-none d-md-table-cell" onclick="window.location.href='{{ url_for('views.player_detail', playerID=data['lc_idPlayer']) }}';">{{ data['lc_losses'] }}</td>
                                <td class="d-none d-xl-table-cell" onclick="window.location.href='{{ url_for('views.player_detail', playerID=data['lc_idPlayer']) }}';">{{ data['lc_gamesFavor'] }}</td>
                                <td class="d-none d-xl-table-cell" onclick="window.location.href='{{ url_for('views.player_detail', playerID=data['lc_idPlayer']) }}';">{{ data['lc_gamesAgainst'] }}</td>
                                <td class="d-none d-xl-table-cell" onclick="window.location.href='{{ url_for('views.player_detail', playerID=data['lc_idPlayer']) }}';">{{ data['lc_gamesDiff'] }}</td>
                                <td class="d-none d-xl-table-cell" onclick="window.location.href='{{ url_for('views.player_detail', playerID=data['lc_idPlayer']) }}';">{{ data['lc_ranking'] }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div><!-- End Row -->
{% endif %}





{% endblock %}

website/templates/rankingELOweek.html
{% extends "base.html" %} {% block title %}XT Padel League{% endblock %} 
{% block content %}

{% if user.is_authenticated and user.pl_type=='Root' %}
<!-- button to calculate full ELO -->
<div class="container">
    <div class="row">
        <div class="col-md-12 text-right">
            <a href="{{ url_for('views.recalculate_ELO_full') }}" class="btn btn-light btn-round px-5"><i class="icon-calculator"></i> Recalcular ELO</a>
        </div>
    </div>
</div>
<br>
{% endif %}

<!-- Row for selection of monday -->
<div class="row">
    <div class="col-lg-12">
        <form method="post">
            <!-- <input type="submit" class="btn btn-light px-3" name="previousMonday" value="Previous" {{ previousMondayDisabled }}> -->
            <select class="select-custom-dashtreme" id="mondaySelect" name="selectedMonday">
                {% for monday in mondays %}
                    <option value="{{ monday }}" {% if monday == selectedMonday %} selected {% endif %}>{{ monday }}</option>
                {% endfor %}
            </select>
            <input type="submit" class="btn btn-light px-2" value="Go">
            <!-- <input type="submit" class="btn btn-light px-3" name="nextMonday" value="Next" {{ nextMondayDisabled }}> -->
        </form>
    </div><!-- End col-lg-12 -->
</div><!-- End Row -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Classificação ELO - {{ selectedMonday }}</h5>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <!-- <th scope="col">#</th> -->
                                <th class="" scope="col">Nome</th>
                                <th class="" scope="col">Ranking ELO</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for data in result %}
                            <tr>
                                <!-- <th scope="row">{{ data['pl_id'] }}</th> -->
                                {% if data['pl_id'] %}
                                <td class=""  onclick="window.location.href='{{ url_for('views.player_detail', playerID=data['pl_id']) }}';">
                                    <img src="{{ url_for('views.display_user_image', userID=data['pl_id'] ) }}" alt="{{ data['pl_name'] }}" class="rounded-circle" width="40" onclick="window.location.href='{{ url_for('views.player_detail', playerID=data['pl_id']) }}';"> 
                                    <!-- <span style="max-width: 50px;"> {{ data['pl_name'] }}</span> -->
                                    <span class="nameContainerELO"> {{ data['pl_name_short'] }}</span>
                                </td>
                                {% else %}
                                <td class=""><img src="{{ url_for('views.display_user_image', userID=0 ) }}" alt="Admin" class="rounded-circle" width="40"> {{ data['pl_name'] }}</td>
                                {% endif %}
                                <td class="" onclick="window.location.href='{{ url_for('views.player_detail', playerID=data['pl_id']) }}';">{{ data['pl_rankingNow'] }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div><!--End Row-->

{% endblock %}